 export  const responsive = {
   superLargeDesktop: {
     // the naming can be any, depends on you.
     breakpoint: { max: 4000, min: 3000 },
     items: 5
   },
   desktop: {
     breakpoint: { max: 3000, min: 1024 },
     items: 4,
   },
   tablet: {
     breakpoint: { max: 1024, min: 464 },
     items: 2
   },
   mobile: {
     breakpoint: { max: 464, min: 0 },
     items: 1
   }
 };

 export const carusel= [
  {
    id:1,
    img_prod_url:'https://img.freepik.com/foto-gratis/amor-romance-perforado-corazon-papel_53876-87.jpg?t=st=1714135817~exp=1714139417~hmac=49a834d2ba85e6a53640e440f53872df87ed16bd54f93d750aaa3f6663c54498&w=996',
    prod_name:'Назва товаруyyyyyyyyyyy',
    prod_discription:'Короткий опис товару',
    price_old:1000,
    price_discont:10,
    price_prod:900,
    name_of_review:'Алла Іванівна',
    stars_from_review:'<i class="fa fa-star" aria-hidden="true"></i>',
    text_review:'Дуже хороший твердотільний накопичувач, швидкий і надійний. В основному я використовую їх під час подорожі як резервний носій для своєї камери та безпілотника. Крім того, слід мати при собі сумку для додаткового захисту. Рекомендований...',
    date_review:'12 Січня, 2024',
    img_traider_url:'traider',
    name_traider:'Продавець',
    stars_traider:'<i class="fa fa-star" aria-hidden="true"></i>',
    qty_reviews:10,
  },
  {
    id:2,
    img_prod_url:'https://img.freepik.com/foto-gratis/amor-romance-perforado-corazon-papel_53876-87.jpg?t=st=1714135817~exp=1714139417~hmac=49a834d2ba85e6a53640e440f53872df87ed16bd54f93d750aaa3f6663c54498&w=996',
    prod_name:'Назва товаруhhh',
    prod_discription:'Короткий опис товару',
    price_old:null,
    price_discont:null,
    price_prod:900,
    name_of_review:'Алла Іванівна',
    stars_from_review:'<i class="fa fa-star" aria-hidden="true"></i>',
    text_review:'Дуже хороший твердотільний накопичувач, швидкий і надійний. В основному я використовую їх під час подорожі як резервний носій для своєї камери та безпілотника. Крім того, слід мати при собі сумку для додаткового захисту. Рекомендований...',
    date_review:'12 Січня, 2024',
    img_traider_url:'traider',
    name_traider:'Продавець',
    stars_traider:'<i class="fa fa-star" aria-hidden="true"></i>',
    qty_reviews:10,
  },
  {
    id:3,
    img_prod_url:'https://img.freepik.com/foto-gratis/amor-romance-perforado-corazon-papel_53876-87.jpg?t=st=1714135817~exp=1714139417~hmac=49a834d2ba85e6a53640e440f53872df87ed16bd54f93d750aaa3f6663c54498&w=996',
    prod_name:'Назва товаруsss',
    prod_discription:'Короткий опис товару',
    price_old:1000,
    price_discont:10,
    price_prod:900,
    name_of_review:'Алла Іванівна',
    stars_from_review:'<i class="fa fa-star" aria-hidden="true"></i>',
    text_review:'Дуже хороший твердотільний накопичувач, швидкий і надійний. В основному я використовую їх під час подорожі як резервний носій для своєї камери та безпілотника. Крім того, слід мати при собі сумку для додаткового захисту. Рекомендований...',
    date_review:'12 Січня, 2024',
    img_traider_url:'traider',
    name_traider:'Продавець',
    stars_traider:'<i class="fa fa-star" aria-hidden="true"></i>',
    qty_reviews:10,
  },
  {
    id:4,
    img_prod_url:'https://img.freepik.com/foto-gratis/amor-romance-perforado-corazon-papel_53876-87.jpg?t=st=1714135817~exp=1714139417~hmac=49a834d2ba85e6a53640e440f53872df87ed16bd54f93d750aaa3f6663c54498&w=996',
    prod_name:'Назва товаруsss',
    prod_discription:'Короткий опис товару',
    price_old:null,
    price_discont:null,
    price_prod:900,
    name_of_review:'Алла Іванівна',
    stars_from_review:`<i class="fa fa-star" aria-hidden="true"></i>`,
    text_review:'Дуже хороший твердотільний накопичувач, швидкий і надійний. В основному я використовую їх під час подорожі як резервний носій для своєї камери та безпілотника. Крім того, слід мати при собі сумку для додаткового захисту. Рекомендований...',
    date_review:'12 Січня, 2024',
    img_traider_url:'traider',
    name_traider:'Продавець',
    stars_traider:'<i class="fa fa-star" aria-hidden="true"></i>',
    qty_reviews:10,
  },
  {
    id:4,
    img_prod_url:'https://img.freepik.com/foto-gratis/amor-romance-perforado-corazon-papel_53876-87.jpg?t=st=1714135817~exp=1714139417~hmac=49a834d2ba85e6a53640e440f53872df87ed16bd54f93d750aaa3f6663c54498&w=996',
    prod_name:'Назва товаруsss',
    prod_discription:'Короткий опис товару',
    price_old:null,
    price_discont:null,
    price_prod:900,
    name_of_review:'Алла Іванівна',
    stars_from_review:`<i class="fa fa-star" aria-hidden="true"></i>`,
    text_review:'Дуже хороший твердотільний накопичувач, швидкий і надійний. В основному я використовую їх під час подорожі як резервний носій для своєї камери та безпілотника. Крім того, слід мати при собі сумку для додаткового захисту. Рекомендований...',
    date_review:'12 Січня, 2024',
    img_traider_url:'traider',
    name_traider:'Продавець',
    stars_traider:'<i class="fa fa-star" aria-hidden="true"></i>',
    qty_reviews:10,
  },
  {
    id:4,
    img_prod_url:'https://img.freepik.com/foto-gratis/amor-romance-perforado-corazon-papel_53876-87.jpg?t=st=1714135817~exp=1714139417~hmac=49a834d2ba85e6a53640e440f53872df87ed16bd54f93d750aaa3f6663c54498&w=996',
    prod_name:'Назва товаруsss',
    prod_discription:'Короткий опис товару',
    price_old:null,
    price_discont:null,
    price_prod:900,
    name_of_review:'Алла Іванівна',
    stars_from_review:`<i class="fa fa-star" aria-hidden="true"></i>`,
    text_review:'Дуже хороший твердотільний накопичувач, швидкий і надійний. В основному я використовую їх під час подорожі як резервний носій для своєї камери та безпілотника. Крім того, слід мати при собі сумку для додаткового захисту. Рекомендований...',
    date_review:'12 Січня, 2024',
    img_traider_url:'traider',
    name_traider:'Продавець',
    stars_traider:'<i class="fa fa-star" aria-hidden="true"></i>',
    qty_reviews:10,
  },
  {
    id:4,
    img_prod_url:'https://img.freepik.com/foto-gratis/amor-romance-perforado-corazon-papel_53876-87.jpg?t=st=1714135817~exp=1714139417~hmac=49a834d2ba85e6a53640e440f53872df87ed16bd54f93d750aaa3f6663c54498&w=996',
    prod_name:'Назва товаруsss',
    prod_discription:'Короткий опис товару',
    price_old:null,
    price_discont:null,
    price_prod:900,
    name_of_review:'Алла Іванівна',
    stars_from_review:`<i class="fa fa-star" aria-hidden="true"></i>`,
    text_review:'Дуже хороший твердотільний накопичувач, швидкий і надійний. В основному я використовую їх під час подорожі як резервний носій для своєї камери та безпілотника. Крім того, слід мати при собі сумку для додаткового захисту. Рекомендований...',
    date_review:'12 Січня, 2024',
    img_traider_url:'traider',
    name_traider:'Продавець',
    stars_traider:'<i class="fa fa-star" aria-hidden="true"></i>',
    qty_reviews:10,
  },
 ]
